apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
    tier: application
spec:
  selector:
    app: backend
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
