apiVersion: v1
kind: Service
metadata:
  name: database-service
  labels:
    app: database
    tier: database
spec:
  selector:
    app: database
  ports:
  - port: 5432
    targetPort: 5432
  clusterIP: None
