# kubernetes/frontend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort  # Makes it accessible from outside
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007
